# Generated by Django 4.0.6 on 2025-02-06 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas/')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(max_length=100)),
                ('faixa_etaria', models.CharField(max_length=50)),
                ('audio', models.FileField(upload_to='audios/')),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='familia_photos/')),
                ('apresentacao_familia', models.FileField(blank=True, null=True, upload_to='apresentacoes/')),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField(blank=True, default=0, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='utilizadores/')),
                ('apresentacao_audio', models.FileField(blank=True, null=True, upload_to='apresentacoes/')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tfc.familia')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField(blank=True, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='comentarios/')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('audio_livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tfc.audiolivro')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tfc.familia')),
            ],
        ),
        migrations.AddField(
            model_name='audiolivro',
            name='gravado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tfc.familia'),
        ),
    ]
