# Generated by Django 4.0.6 on 2025-02-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiolivro',
            name='descricaoAudio',
            field=models.FileField(blank=True, null=True, upload_to='descricao_audios/'),
        ),
    ]
