# Generated by Django 4.0.6 on 2025-02-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfc', '0002_audiolivro_descricaoaudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiolivro',
            name='categoria',
            field=models.CharField(choices=[('Aventura', 'Aventura'), ('Ação', 'Ação'), ('Fantasia', 'Fantasia'), ('Contos de Fadas', 'Contos de Fadas'), ('Mistério', 'Mistério'), ('Animais', 'Animais'), ('Ciência', 'Ciência')], default='Aventura', max_length=50),
        ),
    ]
