# Generated by Django 4.0.6 on 2025-02-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfc', '0003_alter_audiolivro_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiolivro',
            name='categoria',
            field=models.CharField(choices=[('Aventura', 'Aventura'), ('Ação', 'Ação'), ('Fantasia', 'Fantasia'), ('Mistério', 'Mistério'), ('Comédia', 'Comédia'), ('Fábula', 'Fábula'), ('História', 'História'), ('Conto de Fadas', 'Conto de Fadas')], max_length=100),
        ),
    ]
