# Generated by Django 4.0.6 on 2025-04-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfc', '0006_remove_familia_utilizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiolivro',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
