# Generated by Django 4.0.6 on 2025-05-16 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tfc', '0008_alter_audiolivro_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('audiolivro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='tfc.audiolivro')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='tfc.familia')),
            ],
            options={
                'ordering': ['-criado_em'],
                'unique_together': {('familia', 'audiolivro')},
            },
        ),
    ]
