# Generated by Django 4.0.6 on 2025-05-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfc', '0010_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='desenho',
            field=models.ImageField(blank=True, null=True, upload_to='desenhocomentario/'),
        ),
    ]
