# Generated by Django 4.0.6 on 2025-05-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfc', '0011_comentario_desenho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiolivro',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
    ]
