# Generated by Django 5.2.1 on 2025-06-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tfc", "0012_alter_audiolivro_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiolivro",
            name="link_informacoes",
            field=models.URLField(
                blank=True,
                help_text="URL para mais informações (loja, Biblioteca Nacional, etc.)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="audiolivro",
            name="descricao",
            field=models.TextField(max_length=500),
        ),
    ]
