# Generated by Django 5.2.1 on 2025-07-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tfc", "0013_audiolivro_link_informacoes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiolivro",
            name="faixa_etaria",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
